# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hare's Website
email: harerm015@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site contains information about me and some of the things 
  I have worked upon or am currently working.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://Hare-Ram.github.io" # the base hostname & protocol for your site
twitter_username: narendramodi
github_username:  Hare-Ram

# Build settings
markdown: kramdown
